language: java
addons:
  sonarcloud:
    organization: wtekiela
    token:
      secure: HIyfkrDQQwHRgvFLeCzrnPmnJny05RXNtUYZtm6/48TYkeRju/fMMzQE0mY0vOVyJVRsssyQHS+f/vJX/RF3pSHAlbUTQ3Pl90/Q/TfZdWzGnPZh28avoa+HGBATV0tiKdvYgtDI67ywarEZZdfTXrzT/zEkc3g7sz1vd8MfM/s=
git:
  depth: 3
install:
- travis_retry ./gradlew clean assemble -x signArchives --info
script:
- travis_retry ./gradlew check sonarqube --info
env:
  global:
  - secure: IgPA92ioawuSMTZ4DPvghZRaATl4ZW/oeJinqqlDxcJ9wnaKlJjb50mrKrWXs+JMI74Z//En7dwDTPDu69D4IUKiQfHJ70kCv3DVDX/TCnGoEhkOgVSVicpVJtHxTyuXKOPK3ASZwynA989jPku4b3T2uO4VYMuioD1sWMrWJBA=
  - secure: Kg6mpdrNhhQUjIQnTGVagVT8MMG6lvIeGL0ZKQE+gUvOqCz5EI//aPo48RnhZptSQPKHDJXEmtX4eDM61btyrhuF2YKsk9oH5LDhtOP95LQHsjZmspzoRZSOEq6nMBIEsQjmAkK9g3kLFn8bcRmrKhgVvZhcrVQI6VZarPe46Gs=
