name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew clean assemble -x signArchives --info
    - name: Test
      env: # Or as an environment variable
        OS_USER: ${{ secrets.OS_USER }}
        OS_PASS: ${{ secrets.OS_PASS }}
      run: ./gradlew check --info
